package Servlet;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;


/**
 * Created by j-ghazvne on 3/6/17.
 */
public class HomeServlet extends HttpServlet {

    @Override
    public void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setContentType("text/html");
        PrintWriter out = resp.getWriter();

        out.println("<html>");
        out.println("<head>");
//      out.println("<meta charset="utf-8">"):
//      out.println("<meta http-equiv="X-UA-Compatible" content="IE=edge">"):
//      out.println("<meta name="viewport" content="width=device-width, initial-scale=1">"):
        out.println("<!-- Latest compiled and minified CSS -->");
        out.println("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"");
        out.println("integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">");
        out.println("");
        out.println("<!-- Optional theme -->");
        out.println("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\"");
        out.println("integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">");
        out.println("");
        out.println("<!-- Latest compiled and minified JavaScript -->");
        out.println("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"");
        out.println("integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\"");
        out.println("crossorigin=\"anonymous\"></script>");
        out.println("");
        out.println("<link rel=\"stylesheet\" href=\"font-awesome-4.7.0/css/font-awesome.css\">");
        out.println("");
        out.println("<link rel=\"stylesheet\" href=\"Main.css\"/>");
        out.println("</head>");
        out.println("<body>");
        out.println("<div class=\"container\">");
        out.println("<!--Header-->");
        out.println("<div class=\"top-bar\">");
        out.println("<div class=\"panel-body\">");
        out.println("<div class=\"row\">");
        out.println("<div class=\"col-md-10\"> امیرعلی مشایخی");
        out.println("<i class=\"fa fa-user\" aria-hidden=\"true\"></i>");
        out.println("</div>");
        out.println("<div class=\"col-md-2\"> اکبر تیکت");
        out.println("<img id=\"LogoWhite\" src=\"assets/LogoWhite.png\">");
        out.println("</div>");
        out.println("</div>");
        out.println("</div>");
        out.println("<div class=\"line\"></div>");
        out.println("</div>");
        out.println("<!--Main Part-->");
        out.println("<div class=\"row\">");
        out.println("</div>");
        out.println("<!--upper-->");
        out.println("<div class=\"col-md-6 col-centered pull-right\">");
        out.println("<div class=\"choose row\">");
        out.println("<div class=\"twoway col-md-6\">");
        out.println("<a href=\"#\" class=\"ttype2\">دو‌طرفه</a>");
        out.println("</div>");
        out.println("<div class=\"oneway col-md-6\">");
        out.println("<a href=\"#\" class=\"ttype\">یک‌طرفه</a>");
        out.println("</div>");
        out.println("</div>");
        out.println("<div class=\"form form-inline\">");
        out.println("<div class=\"form-inputs row\">");
        out.println("<div class=\"col-md-8\">");
        out.println("<select class=\"form-control input-form\" id=\"sl1\">");
        out.println("<option>1</option>");
        out.println("<option>2</option>");
        out.println("<option>3</option>");
        out.println("<option>4</option>");
        out.println("</select>");
        out.println("</div>");
        out.println("<div class=\"col-md-2\">مبدأ</div>");
        out.println("<i class=\"fa fa-plane fa-lg col-md-2\" aria-hidden=\"true\"></i>");
        out.println("</div>");
        out.println("");
        out.println("<div class=\"form-inputs row\">");
        out.println("<div class=\"col-md-8\">");
        out.println("<select class=\"form-control input-form\" id=\"sel\">");
        out.println("<option>1</option>");
        out.println("<option>2</option>");
        out.println("<option>3</option>");
        out.println("<option>4</option>");
        out.println("</select>");
        out.println("</div>");
        out.println("<div class=\"col-md-2\">مقصد</div>");
        out.println("<i class=\"fa fa-plane fa-lg col-md-2\" aria-hidden=\"true\"></i>");
        out.println("</div>");
        out.println("");
        out.println("<div class=\"form-inputs row\">");
        out.println("<div class=\"col-md-8\">");
        out.println("<input type=\"text\" value=\"۱۳۹۵/۱۱/۲۵\" class=\"form-control \">");
        out.println("</div>");
        out.println("<div class=\"col-md-2\">رفت</div>");
        out.println("<i class=\"fa fa-calendar fa-lg col-md-2\" aria-hidden=\"true\"></i>");
        out.println("</div>");
        out.println("");
        out.println("<div class=\"form-inputs row\">");
        out.println("<div class=\"col-md-8\">");
        out.println("<input type=\"text\" value=\"۱۳۹۵/۱۱/۲۵\" class=\"form-control notacc\" disabled>");
        out.println("</div>");
        out.println("<div class=\"col-md-2\">برگشت</div>");
        out.println("<i class=\"fa fa-calendar fa-lg col-md-2\" aria-hidden=\"true\"></i>");
        out.println("</div>");
        out.println("");
        out.println("<div class=\"row form-inputs\">");
        out.println("<div class=\"col-md-4\">");
        out.println("<h3>نوزاد زیر ۲ سال</h3>");
        out.println("<div class=\"row\">");
        out.println("<div class=\"col-md-8\">");
        out.println("<select class=\"form-control col-md-6\" id=\"sel1\">");
        out.println("<option>۱</option>");
        out.println("<option>۲</option>");
        out.println("<option>۳</option>");
        out.println("<option>۴</option>");
        out.println("</select>");
        out.println("</div>");
        out.println("<div class=\"col-md\">");
        out.println("<i class=\"fa fa-child\" aria-hidden=\"true\"></i>");
        out.println("</div>");
        out.println("</div>");
        out.println("</div>");
        out.println("<div class=\"col-md-4\">");
        out.println("<h3>کودک زیر ۱۲ سال</h3>");
        out.println("<div class=\"row\">");
        out.println("<div class=\"col-md-8\">");
        out.println("<select class=\"form-control col-md-6\" id=\"sel2\">");
        out.println("<option>۱</option>");
        out.println("<option>۲</option>");
        out.println("<option>۳</option>");
        out.println("<option>۴</option>");
        out.println("</select>");
        out.println("</div>");
        out.println("<div class=\"col-md\">");
        out.println("<i class=\"fa fa-child fa-lg\" aria-hidden=\"true\"></i>");
        out.println("</div>");
        out.println("</div>");
        out.println("</div>");
        out.println("<div class=\"col-md-4\">");
        out.println("<h3>بزرگ‌سال</h3>");
        out.println("<div class=\"row\">");
        out.println("<div class=\"col-md-8\">");
        out.println("<select class=\"form-control col-md-6\" id=\"sel3\">");
        out.println("<option>۱</option>");
        out.println("<option>۲</option>");
        out.println("<option>۳</option>");
        out.println("<option>۴</option>");
        out.println("</select>");
        out.println("</div>");
        out.println("<div class=\"col-md\">");
        out.println("<i class=\"fa fa-male fa-lg\" aria-hidden=\"true\"></i>");
        out.println("</div>");
        out.println("</div>");
        out.println("</div>");
        out.println("</div>");
        out.println("");
        out.println("</div>");
        out.println("");
        out.println("<!--<div class=\"form\">-->");
        out.println("<!--<form class=\"form-horizontal\">-->");
        out.println("");
        out.println("");
        out.println("<!--<div class=\"form-group \">-->");
        out.println("<!--<label for=\"in2\" class=\"col-sm-3 control-label pull-right\"><i class=\"fa fa-plane fa-lg \" aria-hidden=\"true\"></i>-->");
        out.println("<!--مقصد-->");
        out.println("<!--</label>-->");
        out.println("<!--<div class=\"col-sm-9 pull-right\">-->");
        out.println("<!--<select class=\"form-control\" id=\"in2\">-->");
        out.println("<!--<option>1</option>-->");
        out.println("<!--<option>2</option>-->");
        out.println("<!--<option>3</option>-->");
        out.println("<!--<option>4</option>-->");
        out.println("<!--<option>5</option>-->");
        out.println("<!--</select>-->");
        out.println("<!--&lt;!&ndash;<input type=\"email\" class=\"form-control\" id=\"in2\" placeholder=\"Email\">&ndash;&gt;-->");
        out.println("<!--</div>-->");
        out.println("<!--</div>-->");
        out.println("<!--<div class=\"form-group \">-->");
        out.println("<!--<label for=\"in2\" class=\"col-sm-3 control-label pull-right\"><i class=\"fa fa-plane fa-lg \" aria-hidden=\"true\"></i>-->");
        out.println("<!--مقصد-->");
        out.println("<!--</label>-->");
        out.println("<!--<div class=\"col-sm-9 pull-right\">-->");
        out.println("<!--<select class=\"form-control\" id=\"in2\">-->");
        out.println("<!--<option>1</option>-->");
        out.println("<!--<option>2</option>-->");
        out.println("<!--<option>3</option>-->");
        out.println("<!--<option>4</option>-->");
        out.println("<!--<option>5</option>-->");
        out.println("<!--</select>-->");
        out.println("<!--&lt;!&ndash;<input type=\"email\" class=\"form-control\" id=\"in2\" placeholder=\"Email\">&ndash;&gt;-->");
        out.println("<!--</div>-->");
        out.println("<!--</div>-->");
        out.println("<!--<div class=\"form-group \">-->");
        out.println("<!--<label for=\"in3\" class=\"col-sm-3 control-label pull-right\"><i class=\"fa fa-plane fa-lg \" aria-hidden=\"true\"></i>-->");
        out.println("<!--رفت-->");
        out.println("<!--</label>-->");
        out.println("<!--<div class=\"col-sm-9 pull-right\">-->");
        out.println("<!--<input type=\"email\" class=\"form-control\" id=\"in3\" placeholder=\"۱۳۹۵/۱۱/۲۵\">-->");
        out.println("<!--</div>-->");
        out.println("<!--</div>-->");
        out.println("<!--<div class=\"form-group \">-->");
        out.println("<!--<label for=\"in4\" class=\"col-sm-3 control-label pull-right \"><i class=\"fa fa-plane fa-lg \" aria-hidden=\"true\"></i>-->");
        out.println("<!--برگشت-->");
        out.println("<!--</label>-->");
        out.println("<!--<div class=\"col-sm-9 pull-right\">-->");
        out.println("<!--<input type=\"email\" class=\"form-control notacc\" id=\"in4\" placeholder=\"۱۳۹۵/۱۱/۲۵\">-->");
        out.println("<!--</div>-->");
        out.println("<!--</div>-->");
        out.println("");
        out.println("");
        out.println("");
        out.println("<!--</form>-->");
        out.println("<!--<div class=\"row\">-->");
        out.println("<!--<div class=\"col-md-4 pull-right\">-->");
        out.println("<!--<h5>نوزاد زیر ۲ سال</h5>-->");
        out.println("<!--<i class=\"fa fa-plane fa-lg\" aria-hidden=\"true\"></i>-->");
        out.println("<!--<select >-->");
        out.println("<!--<option>1</option>-->");
        out.println("<!--<option>2</option>-->");
        out.println("<!--<option>3</option>-->");
        out.println("<!--<option>4</option>-->");
        out.println("<!--<option>5</option>-->");
        out.println("<!--</select>-->");
        out.println("<!--</div>-->");
        out.println("<!--<div class=\"col-md-4 pull-right\">-->");
        out.println("<!--<h5>نوزاد زیر ۲ سال</h5>-->");
        out.println("<!--<i class=\"fa fa-plane fa-lg\" aria-hidden=\"true\"></i>-->");
        out.println("<!--<select >-->");
        out.println("<!--<option>1</option>-->");
        out.println("<!--<option>2</option>-->");
        out.println("<!--<option>3</option>-->");
        out.println("<!--<option>4</option>-->");
        out.println("<!--<option>5</option>-->");
        out.println("<!--</select>-->");
        out.println("<!--</div>-->");
        out.println("<!--<div class=\"col-md-4 pull-right\">-->");
        out.println("<!--<h5>نوزاد زیر ۲ سال</h5>-->");
        out.println("<!--<i class=\"fa fa-plane fa-lg\" aria-hidden=\"true\"></i>-->");
        out.println("<!--<select >-->");
        out.println("<!--<option>1</option>-->");
        out.println("<!--<option>2</option>-->");
        out.println("<!--<option>3</option>-->");
        out.println("<!--<option>4</option>-->");
        out.println("<!--<option>5</option>-->");
        out.println("<!--</select>-->");
        out.println("<!--</div>-->");
        out.println("<!--</div>-->");
        out.println("<!--</div>-->");
        out.println("");
        out.println("<form method='get' action=\"/AkbarTicket/result.jsp\">");
        out.println("<button class=\"search\">جستجو</button>");
        out.println("</form>");
        out.println("</div>");
        out.println("<div class=\"col-md-6 col-centered pull-left\">");
        out.println("<div class=\"css-slideshow\">");
        out.println("<figure>");
        out.println("<img src=\"assets/HomeSlideShow/1.png\" width=\"250\" height=\"350\" />");
        out.println("</figure>");
        out.println("<figure>");
        out.println("<img src=\"assets/HomeSlideShow/2.png\" width=\"250\" height=\"350\" />");
        out.println("</figure>");
        out.println("<figure>");
        out.println("<img src=\"assets/HomeSlideShow/3.png\" width=\"250\" height=\"350\" />");
        out.println("</figure>");
        out.println("<figure>");
        out.println("<img src=\"assets/HomeSlideShow/4.png\" width=\"250\" height=\"350\" />");
        out.println("</figure>");
        out.println("<figure>");
        out.println("<img src=\"assets/HomeSlideShow/5.png\" width=\"250\" height=\"350\" />");
        out.println("</figure>");
        out.println("<figure>");
        out.println("<img src=\"assets/HomeSlideShow/6.png\" width=\"250\" height=\"350\" />");
        out.println("</figure>");
        out.println("<figure>");
        out.println("<img src=\"assets/HomeSlideShow/7.png\" width=\"250\" height=\"350\" />");
        out.println("</figure>");
        out.println("<figure>");
        out.println("<img src=\"assets/HomeSlideShow/8.png\" width=\"250\" height=\"350\" />");
        out.println("</figure>");
        out.println("</div>");
        out.println("<h2 class=\"padd\">سفری ارزان و آسان");
        out.println("با اکبر‌تیکت</h2>");
        out.println("</div>");
        out.println("");
        out.println("</div>");
        out.println("");
        out.println("<div class=\"copyright\"> امیرعلی مشایخی ، جواد الله‌قلی | دانشکده فنی دانشگاه تهران، بهار ۱۳۹۶</div>");
        out.println("");
        out.println("</div>");
        out.println("</body>");
        out.println("</html>");
    }
}
